#!/usr/bin/env bash
##
## macos: macOS-env specific functions.
##

#Open a specfied OSX PrefPane
function osx-pref {
  if [[ ! -z "$1" ]]; then
    if [[ -d "/System/Library/PreferencePanes/$1.prefPane" ]]; then
      open "/System/Library/PreferencePanes/$1.prefPane"
    fi
  fi
}

#Connect to a Tunnelblick configured VPN
function osx-ovpn-connect {
  if [[ -z "$1" ]]; then
    return 1
  fi
  /usr/bin/env osascript <<-EOF
tell application "Tunnelblick"
  connect "$1"
end tell
EOF
}

#Disconnect to a Tunnelblick configured VPN
function osx-ovpn-disconnect {
  if [[ -z "$1" ]]; then
    return 1
  fi
  /usr/bin/env osascript <<-EOF
tell application "Tunnelblick"
  disconnect "$1"
end tell
EOF
}

#Connect to a MacOSX configured VPN
#Config is stored in /Library/Preferences/SystemConfiguration/preferences.plist
function osx-vpn-connect {
  if [[ -z "$1" ]]; then
    return 1
  fi
  /usr/bin/env osascript <<-EOF
tell application "System Events"
  tell current location of network preferences
    set VPN to service "$1"
    if exists VPN then connect VPN
    repeat while (current configuration of VPN is not connected)
      delay 1
    end repeat
  end tell
end tell
EOF
}

#Disconnect from a MacOSX configured VPN
#Config is stored in /Library/Preferences/SystemConfiguration/preferences.plist
function osx-vpn-disconnect {
  if [[ -z "$1" ]]; then
    return 1
  fi
  /usr/bin/env osascript <<-EOF
tell application "System Events"
  tell current location of network preferences
    set VPN to service "$1"
    if exists VPN then disconnect VPN
  end tell
end tell
return
EOF
}

#Set the DNS for all net services
function osx-switch-dns() {
  # Select DNS option
  if [[ "$1" == "CF" ]]; then
    DNS=("1.1.1.1" "1.0.0.1")
  elif [[ "$1" == "GOOG" ]]; then
    DNS=("8.8.8.8" "8.8.4.4")
  else
    DNS="empty"
  fi

  # Assume only one Net location
  NET=$(networksetup -listlocations | head -n1)
  SERVICES=$(networksetup -listallnetworkservices | tail -n +2)
  #ROUTER_IP=$(networksetup -getinfo "$SERVICE" | grep '^Router: ' | cut -f2 -d' ' | xargs)

  echo "$SERVICES" | while read SERVICE ; do
    networksetup -setdnsservers "$SERVICE" $DNS
  done

  echo "The DNS has been set to $DNS"
}

#Attempt WiFi Relogin
function osx-wifi-relogin {
  echo "GATEWAY: http://"$(netstat -rn | grep default | awk '{print $2}')/
  open "http://www.gstatic.com/generate_204"
}

