#!/usr/bin/env bash
##
## misc: Various functions
##

#0x0 Upload
function 0x0-up-file() {
  FILE="$1"
  curl -F'file=@'"$FILE" https://0x0.st

}

#0x0 TinyURL
function 0x0-tinyurl() {
  URL="$1"
  curl -F'shorten='"$URL" https://0x0.st
}

#Countdown function
function countdown() {
  local NOW
  NOW=$(date +%s)
  local END
  END=$((NOW + $1))
  TITLE=${2:-🕒 Countdown}
  MESSAGE=${3:-The countdown of $1 seconds is finished.}
  while (( NOW < END )); do
    case "$OSTYPE" in
      "darwin"* )
        printf "%s\r" "$(date -u -j -f %s $((END - NOW)) +%T)"
        ;;
      "linux-gnu" )
        printf "%s\r" "$(date -u -d @$((END - NOW)) +%T)"
        ;;
      * )
        ;;
    esac
    sleep 0.25
    NOW=$(date +%s)
  done
  terminal-notifier -title "$TITLE" -subtitle "" -message "$MESSAGE" -activate com.googlecode.iterm2
  say "$MESSAGE"
}

CALENDAR="$1"
if [[ -z "$CALENDAR" ]]; then
  CALENDAR="ATTN"
fi

# Parse through calendar to get next Google Hangout link
function gcal-next-hangout() {
  CALENDAR="$1"
  if [[ -z "$CALENDAR" ]]; then
    CALENDAR=$(gcalcli list | grep '@gmail' | sed -e 's/.*owner\([^\s]*\)/\1/g' | xargs)
  fi

  gcalcli agenda $(date -u +"%Y-%m-%dT%H:%M:%SZ") $(date -v'+24H' -u +"%Y-%m-%dT%H:%M:%SZ") --details 'url' --defaultCalendar "$CALENDAR" | grep 'Hangout Link' | grep -o 'http.*' | head -n1
}

# GitDiff function to use vim.
function git_diff() {
  git diff --no-ext-diff -w "$@" | vim -R -
}

# Symbolically link all subdirs within a specified dir in the cwd
function ln-dir-mirror() {
  if [[ -d "$1" ]]; then
    find "$1" -type d -maxdepth 1 -mindepth 1 -exec sh -c 'if [ ! -d $(basename "{}") ]; then ln -s "{}" $(basename "{}"); fi' \;
  fi
}

#Output the timestamp of the last commmand
function last-command-start() {
  COLUMNS=$(tput cols)
  COLUMNS="$(($COLUMNS-1))"
  RED=$(tput setaf 1)
  GREEN=$(tput setaf 2)
  YELLOW=$(tput setaf 3)
  NORMAL=$(tput sgr0)
  TIMESTAMP=$(fc -l -t '%F %T' | tail -n1 | cut -f3-5 -d' ')
  TIMESTAMP=$(echo $TIMESTAMP | xargs echo -n)
  printf '%s%*s%s' "$YELLOW" $COLUMNS "[${TIMESTAMP:2}]" " $NORMAL"
}

#Colorize Manual
function man() {
    env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    LESS_TERMCAP_ue=$(printf "\e[0m") \
    LESS_TERMCAP_us=$(printf "\e[1;32m") \
    man "$@"
}

#Search OUT for MAC address
oui() {
  # Normalize for OUI then search
  MAC="$1"
  MAC=$(echo "$MAC" | awk '{print toupper($0)}')
  MAC="${MAC//:/-}"
  MAC="${MAC:0:8}"

  grep -i "$MAC" <(cat '/tmp/out.txt' 2> /dev/null || curl -s 'http://standards-oui.ieee.org/oui.txt' | tee '/tmp/out.txt')
}

#print out a line w/ title
function printline() {
  if [ "$1" ]; then
    echo ""
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
    echo "$1"
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
    echo ""
  else
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
  fi
}


#Print CSV
function print-csv {
  column -t -s, "$@" | less -F -S -X -K
}

#Print TSV
function print-tsv {
  column -t -s $'\t' "$@" | less -F -S -X -K
}

#Edit compressed JSON w/
function json_pedit() {

  if [ -f "$1" ]; then
    # @TODO: Figure out how to syntax highlight
    jq -r < "$1" | vipe -c 'set syntax=json' | jq -c > tmpfile && mv tmpfile "$1"
    echo "Saved $1"
  fi
}

#SSH without public key
function ssh-nokey() {
  ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no "$@"
}

#Retrieve SSH RSA fingerprint
function ssh-fingerprint-rsa() {
  ssh-keyscan -t rsa "$@" 2>/dev/null | cut -f3 -d' '
}

#Create dir / file in one cms
function touchd() {
  mkdir -p "$(dirname "$1")" && touch "$1"
}

#transfer.sh transport.
transfer-sh() {
    # check arguments
    if [ $# -ne 1 ];
    then
        echo -e "Wrong arguments specified. Usage:\ntransfer /tmp/test.md\ncat /tmp/test.md | transfer test.md"
        return 1
    fi

    # get temporary filename, output is written to this file so show progress can be showed
    TMPFILE="$( mktemp -t transferXXX )"

    # upload stdin or file
    FILE="$1"

    if tty -s;
    then
        BASEFILE="$( basename "$FILE" | sed -e 's/[^a-zA-Z0-9._-]/-/g' )"

        if [ ! -e "$FILE" ];
        then
            echo "File $FILE doesn't exists."
            return 1
        fi

        if [ -d "$FILE" ];
        then
            # zip directory and transfer
            ZIPFILE="$( mktemp -t transferXXX.zip )"
            cd "$(dirname "$FILE")" && zip -r -q - "$(basename "$FILE")" >> "$ZIPFILE"
            curl --progress-bar --upload-file "$ZIPFILE" "https://transfer.sh/$BASEFILE.zip" >> "$TMPFILE"
            rm -f "$ZIPFILE"
        else
            # transfer file
            curl --progress-bar --upload-file "$FILE" "https://transfer.sh/$BASEFILE" >> "$TMPFILE"
        fi
    else
        # transfer pipe
        curl --progress-bar --upload-file "-" "https://transfer.sh/$FILE" >> "$TMPFILE"
    fi

    # cat output link
    cat "$TMPFILE"
    echo

    # cleanup
    rm -f "$TMPFILE"
}

#Shortcut to open URL
function wopen() {
  if [[ $1 == "http://"* || $1 == "https://"* ]]; then
    open "$1"
  else
    open "http://$1"
  fi
}
