#!/usr/bin/env bash

##########ALIASES###############################################################
alias ..1='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ..4='cd ../../../..'
alias ..5='cd ../../../../..'
alias ..6='cd ../../../../../..'
alias ..7='cd ../../../../../../..'
alias ..8='cd ../../../../../../../..'
alias ..9='cd ../../../../../../../../..'

#Apache Shortcuts
alias a-gra='sudo service httpd graceful'
alias a-lo='sudo service httpd reload'
alias a-resta='sudo service httpd restart'
alias a-sta='sudo service httpd start'
alias a-stat='sudo service httpd status'
alias a-end='sudo service httpd stop'
alias a-drush='sudo -u apache drush'
alias a-git='sudo -u apache git'

#Tag git repo
alias ctagit='ctags -R -f ./.git/tags .'

########## DIFF ################################################################
command -v colordiff >/dev/null 2>&1 && { alias diff="colordiff"; }
########## DIFF ################################################################

##Silver search w/ hidden & Git dirs excluded
alias ag='ag --hidden --ignore-dir .git'

#Shortcut Drush
alias dr='drush'

#Today's GCal events
alias gcal-today='gcalcli agenda $(date -u +"%Y-%m-%dT%H:%M:%SZ") $(date -v'+24H' -u +"%Y-%m-%dT%H:%M:%SZ") --refresh --details 'url' --defaultCalendar'

#Colorize grep
alias grep='grep --color=always'

#Retrieve git remote
alias git-remote-current="git branch -vv | grep '\* ' | sed 's/.*\[\(.*\)\].*/\1/g; s/.*(HEAD detached at \(.*\)).*/\1/g; s/\* \(.*\)                           .*/\1/g; s/\*\ \([^ ]*\)\ .*/\1/g'"

#Git push all branches
alias git-push-branches='git push -u $(git config --get branch.master.remote) --all'

#Shortcut detailed listing
alias lsl='ls -al'

#No RC Vim
alias nrcvim='vim -u NONE'

#Toggle Show/Hide hidden files in Finder
alias osx-file-hide='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias osx-file-show='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'

#Network setup
alias osx-net-change='networksetup -switchtolocation'

#Previous dir
alias pd='cd -'

#OS-dependant aliases
case "$OSTYPE" in
  "darwin"* )
    #SVIM = root edit w/ .vimrc config
    alias svim='sudo vim'
    alias shuf='gshuf'
    ;;
  "linux-gnu" )
    #SVIM = root edit w/ .vimrc config
    alias svim='sudoedit'
    ;;
  * )
    ;;
esac

#Repeat last command as root
alias resu='sudo $(fc -ln -1)'

#Setup Toggl
alias toggl='nvm use 5.0 && toggl'

#Use Tree w/ hidden & Git dirs excluded
alias tree='tree -a -I .git'

########## VIM #################################################################
#Use MacVim In Terminal
if [ -f /Applications/MacVim.app/Contents/MacOS/Vim ]; then
  alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
  alias mvim='/Applications/MacVim.app/Contents/MacOS/Vim'
fi
########## VIM #################################################################

#Run vim w/ vundle config and plugin clean & quit flags
alias vundle-clean='vim -u "$HOME/.vundle.vimrc" +PluginClean! +qall'

#Run vim w/ vundle config and plugin install & quit flags
alias vundle-install='vim -u "$HOME/.vundle.vimrc" +PluginInstall +qall'

#Run vim w/ vundle config and plugin update & quit flags
alias vundle-update='vim -u "$HOME/.vundle.vimrc" +PluginUpdate +qall'

#Get external IP
alias wanip="dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com | tr -d '\"'"
alias wanipv6="dig -6 TXT +short o-o.myaddr.l.google.com @ns1.google.com | tr -d '\"'"

#Colorize watch
alias watch='watch -c '

#WGet to StdOut
alias wgetout='wget -qO- '
##########ALIASES###############################################################
