#!/usr/bin/env zsh
##
## misc: Various functions
##

# Execute on every dir change
function chpwd() {
  emulate -L zsh

  git-aliases
}

# Execute on ZSH exit
function zshexit() {

}

# Check bin existence
function exists { which $1 &> /dev/null }

# Activate Percol on Ctrl+R
if exists percol; then
    function percol_select_history() {
        local tac
        exists gtac && tac="gtac" || { exists tac && tac="tac" || { tac="tail -r" } }
        BUFFER=$(fc -l -n 1 | eval $tac | percol --query "$LBUFFER")
        CURSOR=$#BUFFER         # move cursor
        zle -R -c               # refresh
    }

    zle -N percol_select_history
    bindkey '^R' percol_select_history
fi

# Set the ZSH theme then touch .zshrc to have antigen pick it up.
function zsh-theme() {
  if [ -z "$1" ]; then
    rm ~/.zshrc.theme 2> /dev/null || true
  else
    echo "$1" > "$HOME/.zshrc.theme" 
  fi
  touch "$HOME/.zshrc"
}

########## OMZ/NVM #################################################################
export NVM_DIR="$HOME/.nvm"

#@TODO: OMZ has an issue with booting NVM, use wrapper function until resolved.
function nvm() {
  if [ -z "$NVM_BOOTED" ]; then
    export NVM_BOOTED="1"
    unset -f nvm
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
    nvm "$@"
  fi
}

autoload -U add-zsh-hook
load-nvmrc() {
  if [[ -f .nvmrc && -r .nvmrc ]]; then
    nvm use
  fi
}
add-zsh-hook chpwd load-nvmrc
